# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      env:
        twitter_access_token : ${{secrets.TWITTERACCESSTOKEN}}
        twitter_access_token_secret : ${{secrets.TWITTERACCESSTOKENSECRET}}
        twitter_consumer_key : ${{secrets.TWITTERCONSUMERKEY}}
        twitter_consumer_key_secret : ${{secrets.TWITTERCONSUMERSECRET}}
      run: mvn --file DeuStock/pom.xml --batch-mode --update-snapshots verify
