# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
  build:
    runs-on: ubuntu-latest
    services:
        mysql:
            image: mysql:8.0
            env:
                MYSQL_USER: deustock_user1
                MYSQL_PASSWORD: 12345
                MYSQL_ROOT_PASSWORD: 12345
                MYSQL_DATABASE: deustockdb
            ports:
                - '3306:3306'
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
              
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Create database schema
      run: |
        cd DeuStock
        mvn compile datanucleus:enhance
          
    - name: Build with Maven (Server)
      env:
        twitter_access_token : ${{secrets.TWITTERACCESSTOKEN}}
        twitter_access_token_secret : ${{secrets.TWITTERACCESSTOKENSECRET}}
        twitter_consumer_key : ${{secrets.TWITTERCONSUMERKEY}}
        twitter_consumer_key_secret : ${{secrets.TWITTERCONSUMERSECRET}}
        reddit_username_secret : ${{secrets.REDDITUSERNAMESECRET}}
        reddit_password_secret : ${{secrets.REDDITPASSWORDSECRET}}
      run: mvn --file DeuStock/pom.xml --batch-mode --update-snapshots verify

    - name: Upload server coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: server
        directory: ./DeuStock

    - name: Build with Maven (Client)
      env:
        twitter_access_token : ${{secrets.TWITTERACCESSTOKEN}}
        twitter_access_token_secret : ${{secrets.TWITTERACCESSTOKENSECRET}}
        twitter_consumer_key : ${{secrets.TWITTERCONSUMERKEY}}
        twitter_consumer_key_secret : ${{secrets.TWITTERCONSUMERSECRET}}
        reddit_username_secret : ${{secrets.REDDITUSERNAMESECRET}}
        reddit_password_secret : ${{secrets.REDDITPASSWORDSECRET}}
      run: mvn --file DeuStock/pom.xml --batch-mode --update-snapshots clean compile exec:java && mvn --file DeustockClient/pom.xml --batch-mode --update-snapshots verify
      
    - name: Upload client coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: client
        directory: ./DeustockClient
