# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        mysql:
            image: mysql:8.0
            env:
                MYSQL_USER: deustock_user1
                MYSQL_PASSWORD: 12345
                MYSQL_ROOT_PASSWORD: 12345
                MYSQL_DATABASE: deustockdb
            ports:
                - '3306:3306'
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
              
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Create database schema
      run: |
        cd DeuStock
        mvn compile datanucleus:enhance

    - name: Build and analyze 
      env:
        twitter_access_token : ${{secrets.TWITTERACCESSTOKEN}}
        twitter_access_token_secret : ${{secrets.TWITTERACCESSTOKENSECRET}}
        twitter_consumer_key : ${{secrets.TWITTERCONSUMERKEY}}
        twitter_consumer_key_secret : ${{secrets.TWITTERCONSUMERSECRET}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn --file DeuStock/pom.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    

    - name: Build with Maven (Client)
      run: mvn --file DeustockClient/pom.xml --batch-mode --update-snapshots verify
      